### ISSUE TITLE
Sample files not in usable format

### ISSUE THREAD

**Issue by ericgibsontaylor** [SOLV-Code/SPAT-Apps#5]
The sample files (e.g. SpawnerRecruit) have the year column as Year rather than yr.
Would be great if the user could select which field would be the time/date and allow the user to select between Year or date. Correlations can be run based on an index number field but results can be displayed as year or as.Date().

Additionally, the SpawnerRecruit file has multiple stocks which clogs up the tool.

**Comment by SOLV-Code** [comment]
Two separate issues here.

## Issue 1
The sample files on drop box were old csv from tests for different apps with different kind of data.
I've replaced them with a working example called *SPATData_CorrApp_CU_Spn.csv*. Once there are more apps, we'll have to keep some clear description of which data file works with which app.

## Issue 2
Giving the user the option to select the time variable would be great, but requires substantial code on the back-end to make all the data handling dynamic.  I'm adding that to the feature requests at #9, but under "long-term requests"...


Issue 1 is dealt with, Issue to added to the inventory, so closing this thread.
