### ISSUE TITLE
Correlation matrix does not include years after 2010

### ISSUE THREAD

**Issue by ericgibsontaylor** [SOLV-Code/SPAT-Apps#6]
When selecting years for the correlation matrix plot, if 2010-present is selected, all correlations are 1 or -1. If 2011-present is selected, there is an error but not sure why. If this is designed maybe add informative error message.

**Comment by SOLV-Code** [comment]
You found an underlying source for errors that for which we'll need to build in some safeguards.
Basically, if you select a time window with very few values, then it starts acting weird. Once you get to 2 values it is either a positive or a negative correlation. If only 1 value in the window, then it fails b/c it needs at least 2 for the correlation calc.

I'll add this to the feature requests at #9 and close here.
